baseurl = "https://waterloofarmholidays.co.uk/"
relativeURLs = false
canonifyURLs = false
title = "Waterloo Farm Holidays"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true
hasCJKLanguage = false
sectionPagesMenu = ""
buildFuture = true

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/hero/orchard_track.jpg"
  SEOTitle = "Waterloo Farm Holidays | Luxury Holiday Lets in the Countryside"
  description = "Discover our collection of 6 beautiful holiday lets at Waterloo Farm. Perfect for couples, families, and groups seeking peaceful countryside retreats with modern comfort."
  keyword = "holiday lets, countryside accommodation, farm holidays, vacation rentals, rural retreats, family holidays, pet friendly cottages, waterloo farm, luxury cottages, self catering"
  slogan = "Escape to the Cornish Countryside"
  upstreamAttribution = false

  image_404 = "img/404-bg.jpg"
  title_404 = "Page Not Found"
  omit_categories = true

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Beautiful holiday lets in the heart of the countryside. Your perfect escape awaits."
  #sidebar_avatar = "img/waterloo-farm-logo.png"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/hero/orchard_track.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  # Artalk comments
  # Follow https://artalk.js.org/ to set up your own server
  artalk_enable = false
  artalk_server = ""
  artalk_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles
  reward = false
  # reward_guide = ""

  friends = false
  bookmarks = false
  about_me = false

  # Last posts
  last_posts = false
  #last_posts_title = "LAST POSTS"
  #last_posts_count = 5

  # Include any custom CSS and/or JS files, url or relative to /static folder
  custom_css = ["css/custom.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = false
  email          = "info@waterloofarmholidays.co.uk"
  facebook       = "https://www.facebook.com/pages/Waterloo-Farm-Holidays/171360599549442"
  #twitter        = ""
  instagram      = "https://www.instagram.com/waterloofarmhols"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  
  [[params.additional_menus]]
  title =  "Accommodation"
  href =  "accommodation"
  [[params.additional_menus]]
  title =  "Activities"
  href =  "activities"
   [[params.additional_menus]]
  title =  "Food & Drink"
  href =  "food-and-drink"
    [[params.additional_menus]]
  title =  "Calendar"
  href =  "calendar"
  [[params.additional_menus]]
  title =  "Contact"
  href =  "contact"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']
